### ISSUE TITLE
Add jpmckinney on PyPI

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#103]
For at least ocdsmerge and extension_tester.

I'm jpmckinney.

kindly is owner of https://pypi.python.org/pypi?%3Aaction=search&term=David+Raznick&submit=search

**Comment by jpmckinney** [comment]
Pinging @kindly

**Comment by kindly** [comment]
@jpmckinney added you as owner of the 3 relevant packages

**Comment by jpmckinney** [comment]
Thanks! For my own reference, https://pypi.org/user/jpmckinney/ has all package listings I'm owner of.
