### ISSUE TITLE
Retiring dev-discuss mailing list

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#108]
* What are the criteria for Owner and Manager?
* Can I be made Owner on both?

Lists:

* https://groups.google.com/a/open-contracting.org/forum/#!forum/standard-discuss
* https://groups.google.com/a/open-contracting.org/forum/#!forum/dev-discuss

**Comment by jpmckinney** [comment]
@timgdavies Please make me Owner of both Google Groups.

**Comment by timgdavies** [comment]
I've added you to both groups. 

https://groups.google.com/a/open-contracting.org/forum/#!forum/dev-discuss has not been used since it was established, so I suggest we retire it.

**Comment by jpmckinney** [comment]
For dev-discuss, under Manage, I did:

* Advanced > Directory > uncheck List this group in the directory
* Permissions > Basic permissions
  * View topics: uncheck all (was all checked)
  * Post: uncheck all (was all checked except Public)
  * Join the group: Anyone in the organization can ask (was Public)
