### ISSUE TITLE
GitHub: Restrict third-party application access

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#11]
I'd like to [restrict third-party application access](https://github.com/organizations/open-contracting/settings/oauth_application_policy/confirm), so that we can centrally control what gets integrated. (The ['integrations'](https://github.com/open-contracting/standard-development-handbook/issues?q=is%3Aissue+is%3Aopen+label%3AIntegrations) tag shows that things are a bit uncontrolled.)

I don't anticipate anything will fail severely (none of the integrations are mission critical), but I wanted to double-check beforehand.

* [x] Please give me the go-ahead and I'll proceed with configuring this.

**Comment by Bjwebb** [comment]
I'm happy to see this enabled. @timgdavies could you double check?

**Comment by jpmckinney** [comment]
I've enabled it. I don't anticipate any action, unless anyone was using an SSH key created before February 2014 (in which case you'll have to generate a new one). The list of consequences of enabling this is at: https://help.github.com/articles/about-oauth-app-access-restrictions/#setting-up-oauth-app-access-restrictions

"Hooks created by users and hooks created before May 2014 will not be affected." so it seems like there may be no action required at the moment. We'll quickly see whether non-critical integrations break, though :)
