### ISSUE TITLE
GitHub: Teams (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#12]
* [ ] Document why the repository access is as it is for each team
  * https://github.com/orgs/open-contracting/teams/developers/repositories
  * https://github.com/orgs/open-contracting/teams/ilda/repositories
  * https://github.com/orgs/open-contracting/teams/standard/repositories
* [ ] Document why people would belong to a given team
  * https://github.com/orgs/open-contracting/teams/developers/members
  * https://github.com/orgs/open-contracting/teams/ilda/members
  * https://github.com/orgs/open-contracting/teams/standard/members
* [ ] Add a script to https://github.com/open-contracting/standard-maintenance-scripts for checking and adding repositories to teams based on our policy

Cleanup:
* [x] Review teams' repository access (none of the teams' accesses make sense to me, e.g. Developers can only read mapping-sheet-generator, Standard only accesses three extensions)
* [x] Delete the [europython sprint](https://github.com/orgs/open-contracting/teams/europython-sprint/edit) and [Non-tech contributors](https://github.com/orgs/open-contracting/teams/non-tech-contributors/edit) teams?

**Comment by timgdavies** [comment]
Assigning me and James to discuss and document who should have access to what, and repository access policy. 

No problem to delete those extra teams: they are legacy.

**Comment by jpmckinney** [comment]
@timgdavies Can we schedule some time to close this issue? It should take no more than 30 mins.

**Comment by jpmckinney** [comment]
CRM had the following intentions:

We will create the following teams:

* Standard authors - for people who should be able to commit to the standard branches (except for protected branches) directly
* Open Data Services - for members of the Open Data Services team
* Open Contracting Partnership - for members of the Open Contracting Partnerships team
* ILDA - for members of the Latin America Helpdesk Hub
* Helpdesk - for everyone involved in helpdesk tasks

**Comment by jpmckinney** [comment]
I changed ["Default repository permission"](https://github.com/organizations/open-contracting/settings/member_privileges) to "Write" and eliminated all teams.

The alternative is to decide which repositories which groups of people should have write access to. However, considering all default branches are protected, there is low risk to giving away write access. We can further protect from unreviewed merges by implementing codeowners #56.
