### ISSUE TITLE
Translation documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#120]
TODOs in:

* [ ] http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/
* [x] http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/terminology/ @ColinMaudry 
* [x] http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/translation/
* [x] http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#push-and-pull-updated-translations

Copying some content from "Translation and localization: follow up email" email thread regarding the above TODOs:

# Terminology

http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/terminology/

* [x] Add link to Google spreadsheet @ColinMaudry 

We agreed on centralizing terminology. We saw that Transifex may be suitable for basic terminology management, since: it has a comment field that can be used for a definition in each language; it has a CSV export for broader publication. For example, the French glossary: https://www.transifex.com/OpenDataServices/open-contracting-standard-1-1/glossary/fr/

@ColinMaudry is working on the glossary. This page in the handbook should describe where the glossary is ultimately stored, and any processes around changes to it.

# Two categories of updates in the source

* [x] http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/ Related TODO: "Describe the workflow."

There are two categories of updates of the source content:

* major: those that require updating the translation (= the meaning has changed)
* minor: those that don't (= the meaning hasn't changed)

The problem is the English editor can't tell Transifex what sort of change it is. The result is that the translators see that some strings need to be translated, but they don't know right away whether:

* it's a new string that never was translated
* it's a string that was translated and just needs to be revalidated (= fetched from "Suggestions")
* it's a string that was translated but that has changed enough to require changes in the translation

In this situation, the "Suggestions" menu tells you what translations have been made for similar source strings, such as the string it was before the change. There you can see what has changed in the source, and whether the previous translation was fine or if it requires changes. But when one deals with tens of strings to check, assessing the situation for each string is quite time consuming.

Communication is key here: those who update the English source must tell the translation teams what sort of changes (minor or major) have been done, and on which resource (= Web page). This way, translators can swiftly update the translation, without needing to assess the situation on each string. However, this assumes:

* those who update the source know how to contact all the translators (e.g. email addresses)
* the translators are available

**Comment by jpmckinney** [comment]
@ColinMaudry wrote:

Updating a translation implies many small actions. The tooling is obviously a key part, but the business process is the glue that make the people and the tools in action to produce the expected result. Designing this process is about thinking of:

* roles: who does what
* sequences of actions: what do we do in each identified case, and in what sequence
* what tool for what purpose: we have certain tools available, some can easily be created (small scripts), how to we take advantage of them
* documenting it all

@timgdavies responded:

Agreed. I think best process would be:

* Document ideal translation process there
* We review whether there are any technical blockers to implementing that process
* @Bjwebb and I address any technical blockers we can within available resources, and/or find documentation work-arounds for trickier things

**Comment by jpmckinney** [comment]
Related PR: https://github.com/open-contracting/standard-development-handbook/pull/105

**Comment by jpmckinney** [comment]
Noting for posterity that the chart source is: https://www.lucidchart.com/documents/edit/3d906148-5ed8-41a4-b48d-8d3ec3aed1d4

**Comment by jpmckinney** [comment]
* [ ] @Bjwebb Can you ensure that your [OCDS Notes for translators](https://docs.google.com/document/d/1fHaMWxGnWxm0ZyW3pYLxd_ZWI6uYW30Zl5EFNDjCGkU/edit) document is reflected in http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/? If so, we can move it to a Archive folder in Google Drive.

**Comment by jpmckinney** [comment]
Moved from #4:

* [ ] Document the automatic and manual translation steps (I anticipate this will be covered by the already planned documentation work)
* [ ] Describe the consequences of different types of changes on the translation process (I anticipate this will be covered by a discussion of minor and major updates to source content)
* [ ] Document the timeline/staging process, as we approach release (e.g. freezing English strings to avoid interfering with the translation process)

**Comment by jpmckinney** [comment]
* [ ] Replace *someone* mentions in terminology.md @ColinMaudry

**Comment by jpmckinney** [comment]
@tlacoyodefrijol See "Transifex as our translation tool" in the issue description. We had discussed last year that you would prepare guidelines/tips on the best ways to use Transifex. Is that still something you can take on?

**Comment by tlacoyodefrijol** [comment]
@jpmckinney sure, I can work on that. Is there a CRM issue related to this?

**Comment by jpmckinney** [comment]
@tlacoyodefrijol I've now created 3034.

**Comment by jpmckinney** [comment]
@ColinMaudry terminology.md has an ambiguous "someone" towards the end. Can you make a PR to update that? There's also a 'TODO' in that document. Can you also add a link to the terminology spreadsheet?

**Comment by ColinMaudry** [comment]
I have done a [new PR](https://github.com/open-contracting/standard-development-handbook/pull/128).

To kickstart, I think we need someone to take on the role of coordinator.

1. to get an SME to write the definitions for the English terms, typically someone from OCP who is knowledgeable in public contracing. Reminder: it's not absolute definitions, but the definitions of the terms in the frame of the OCDS and of OCP activities.
2. then get someone to do or complete the languages and language variants (SMEs)
3. then the proofreaders to check the work of the SMEs

**Comment by jpmckinney** [comment]
One last todo (moved to #151), otherwise all done.

For 1.1.3 translation, I'll be coordinator for all languages just to get things moving.

For terminology, Tim is starting on Colin's (1) in CRM issue 2480.

For (2) and (3), we'll continue to follow http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/terminology/#management-tasks
