### ISSUE TITLE
GitHub: Migrate to new organization features

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#13]
https://github.com/orgs/open-contracting/migration/customize_member_privileges

I suggest:

* Set the visibility of your teams: Make your current teams visible to all members (default, recommended)
* Choose the default repository permission level: Read (recommended)
* Choose whether members can create new repositories: Allow repository creation (default, recommended)

**Comment by timgdavies** [comment]
I would be happy with this change. 

Tagging @Bjwebb to confirm.

**Comment by Bjwebb** [comment]
Looks good to me.

**Comment by jpmckinney** [comment]
Done. GitHub continues to display the alert about the new features, which I've dismissed now.
