### ISSUE TITLE
How are codelists pulled into standard repository?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#137]
There are three codelists in `standard/docs/en/extensions/codelists`

* bidStatistics.csv
* bidStatus.csv
* locationGazetteers.csv

For some reason there's also `standard/schema/codelists/locationGazeteer.csv`

However, these are not the only codelists within core extensions.

**Comment by jpmckinney** [comment]
@timgdavies We should have instructions for this before 1.1.3 release.

**Comment by jpmckinney** [comment]
I see that the bids readme has a `csv-table-no-translate` directive referencing its two codelists. I don't think there's a need for the location codelists.

**Comment by timgdavies** [comment]
I was just reviewing this - and I believe it has been manual in the past. I propose to add a script for this, and to document that in the handbook.

**Comment by jpmckinney** [comment]
Should the script only pull in what's necessary? (i.e. not all core extension codelists, but only those in use by Sphinx directives?)

**Comment by jpmckinney** [comment]
You wrote in https://github.com/open-contracting/standard-development-handbook/pull/142 that you updated the script, but I don't think you pushed the commit https://github.com/open-contracting/standard/tree/1.1.3-dev

I have a few PRs open that I'll probably just merge, as I don't want to have to resolve conflicts for days https://github.com/open-contracting/standard/pulls
