### ISSUE TITLE
GitHub: Require two-factor authentication?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#14]
Opinions of requiring 2FA? We'd of course ensure everyone was setup before [requiring it](https://github.com/organizations/open-contracting/settings/security).

**Comment by timgdavies** [comment]
I would be happy with this from our perspective. 

I think worth reviewing with the OCP team - who are probably the most likely to be travelling and logging into things where 2FA might be trickier. 

Are there any known inclusion impacts in terms of countries who can't get 2FA SMS and so have a trickier time engaging?

**Comment by jpmckinney** [comment]
Related #18. Here's the list of people with 2FA disabled: https://github.com/orgs/open-contracting/people?utf8=✓&query=%20two-factor%3Adisabled

We can start by getting the helpdesks using 2FA :)

I use an authenticator app for GitHub, which works offline.

**Comment by jpmckinney** [comment]
Closing as duplicated in CRM.
