### ISSUE TITLE
Glossary script 

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#148]
Copying @ColinMaudry's comment in #128:

For the last part of the process, the CSVs can be downloaded via the following URL:

```
https://docs.google.com/spreadsheets/d/1PvlA2WWtP9KJpnkhuYGx5ExHmHwwvaA54VX62piF86k/export?format=csv&id=1PvlA2WWtP9KJpnkhuYGx5ExHmHwwvaA54VX62piF86k&gid=N
```

The final `N` is the number of the sheet to download, `0` being the Source sheet. All sheets must always be downloaded at the same time to avoid discrepancies.

According to [Transifex documentation](https://docs.transifex.com/setup/glossary/uploading-an-existing-glossary), to upload theses CSVs and update the glossaries the column headers should be different from what is used in the Google spreadsheet:

- `POS` instead of `Class` (I fixed that)
- language code instead of `Translation` (I fixed that)
- `comment` instead of `definition`: I won't change this one in the spreadsheet, as we want the SMEs to know this column is for definitions and not mere comment
- the `Comment_language` column should be renamed before importing, and its content may be merged with the definition, as we can only import one auxiliary field named `comment_language`

I will do some testing with a test organization, but it seems like some scripting will be necessary to prepare the CSVs for upload. That script would perform the following actions:

1. Downloading the CSVs from Google
2. Uploading them to Github
3. Preparing them for Transifex upload (language variants such as es-MX may not be uploaded to Transifex, as they are not translation targets)

I found no way to programmatically update a Transifex glossary, as the command line tool only enables to interact with a translation project. This update is consequently manual, via Transifex webapp.

**Comment by jpmckinney** [comment]
(Opening a new issue as the other one is a PR.) @ColinMaudry Are you planning to write this script? Ideally it would be a Python script that we'll keep in https://github.com/open-contracting/standard/tree/1.1-dev/standard/schema/utils If not, it should not take long for me to write something.

**Comment by ColinMaudry** [comment]
That would be fun, but I really don't have time these days. Plus I'm better at bash that at Python.

But I can't wait to see the result!

**Comment by jpmckinney** [comment]
@ColinMaudry Please have a look at the CSVs and let me know if they conform to your description: https://github.com/open-contracting/glossary/tree/master/glossaries

**Comment by ColinMaudry** [comment]
That looks good! I have uploaded fr.csv to a test organization after adding comments in it, and that worked.

I see that in Transifex, we didn't specify region codes for French and Spanish. That's good, since our objective is to propose generic translations 👍
