### ISSUE TITLE
GitHub: OCDS extension descriptions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#15]
* [x] Author guidance / template for OCDS extension descriptions

Presently, descriptions are all over the place, and sometimes include 'draft' in the description, even if elsewhere they are no longer 'draft'. To give a sense:

1. Extention to standard to convert packages to API responses
1. Draft extension for PPP extension
1. Draft shareholders extension for PPPs
1. For including extra contact points on each organization. Useful when each contact point deals only in a particular language or group of languages.
1. Bid statistics and detail extension
1. Draft extension to provide a budget breakdown
1. A draft extension to separate project and budget information (upgrade proposal)
1. The charges extension is used to record details of the total charges that are estimated or applied to users or government during the operation of a Public Private Partnership contract. 
1. Adds an array of organizationReferences to the contract section OCDS to support explicit declaration of the signatories to a contract.
1. To allow explicit declaration of suppliers within the contracts block.
1. Extending the documents block with page numbers, access details and authorship information
1. OCDS Enquiries extension
1. Under some procurement rules and processes, to extend the duration or value of a contract, or to make other substantial alterations, requires a new contract to be signed. This extension allows these relationships between two or more contracts in the same contracting process to be made explicit.
1. Capturing details of the finance arranged for a contract, including loans, grants and other finance sources.
1. Updated draft of the OCDS location extension (for 1.1)
1. A tender process may be divided into lots, where bids and awards can be made against one or more lots. 
1. The metrics extension supports publication of forecasts (planning stage), targets (tender stage), agreed performance targets (award and contract stage) and results (implementation stage).
1. Documents at the milestone level were deprecated in OCDS 1.1. This extension re-introduces the ability to attach documents to each individual milestone.
1. This extension adds a buyer property to the contract section of an OCDS release.
1. Draft participation fee extension
1. A draft extension for the OCDS 1.1 upgrade modelling of Organizations
1. For classifying organisations as micro, sme or large.
1. This extension introduces a performance failures array to the implementation section of OCDS, based on the performance failures reporting table defined in the framework for disclosure in PPPs.
1. For providing overall process titles and descriptions, often to give a free-text summary of the contracting process as a whole.
1. Draft qualification extension for PPPs
1. Draft related process extension for OCDS V1.1 upgrade and PPP extension
1. Requirements extension for OCDS V1.1 upgrade
1. Draft Extension (training activity)
1. An extension to capture details of tariffs for Public Private Partnership projects
1. Adds a relatedImplementationMilestone property to the transactions object so that disbursements can be linked with their associated milestone.
1. For the development of resources to adapt and apply OCDS in the context of Public Private Partnerships (PPPs)
1. OCDS for Trade (draft implementation profile)

**Comment by edugomez** [comment]
We should have some guidance on describing extensions to avoid the current situation described in this issue. Some suggestions:

- There is not no maximum length for the description, but it should be as concise as possible. In any case, do not sacrifice clarity for the sake of brevity
- Refer to the part(s) of the schema the extension is modifying
- Do not include in the description the development status of the extension (e.g. _draft_). If you need to add current status, do so in a readme file (which is much more visible and less prone to be forgotten and not updated)
- Avoid self-evident descriptions: e.g. _OCDS Enquiries extension_ for _ocds_enquiry_extension_. The name of the extension should be as self-documented as possible, which means that _ocds_enquiry_extension_ is right. However, the description should be giving some additional info,not just repeating the name

**Comment by jpmckinney** [comment]
Documented at https://github.com/open-contracting/standard_extension_template#extension-descriptions

We should now edit the descriptions to align with the documented approach.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/ocds-extensions/issues/64 for visibility.
