### ISSUE TITLE
Describe the process for selecting translators and reviewers and managing permissions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#151]
A 'todo' in http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/

**Comment by jpmckinney** [comment]
https://www.transifex.com/OpenDataServices/teams/

**Comment by ColinMaudry** [comment]
What's a TOR process?

**Comment by jpmckinney** [comment]
Terms of reference. OCP advertises an opportunity and invites people to submit applications/quotes/proposals, then interviews and selects candidates.
