### ISSUE TITLE
Extension name guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#16]
* [x] Author extension name guidance

I have a vague memory of seeing guidance on how to name extensions (something like `ocds_[name]_extension` ([found it](http://crm.open-contracting.org/projects/ocds/wiki/GitHub)). Extensions that don't conform are:

* api_extension
* ocds-riskAllocation-extension
* ocds-shareholders-extension
* ocds_performance_failures

We may add suggestions, e.g. that `name` should be based on a JSON Pointer fragment for the primary field that is being added, or the name of the primary object being added. This is true of:

1. additionalContactPoints
1. bid (Bid)
1. charges
1. contract_signatories (Contract_signatories)
1. contract_suppliers (Contract_suppliers)
1. enquiry (Enquiry)
1. extendsContractID
1. finance
1. location (Location)
1. lots
1. metrics
1. milestone_documents (Milestone_documents)
1. participationFee (ParticipationFee)
1. parties
1. requirements
1. tariffs

It's not true of:

1. budget_breakdown (budgetBreakdown)
1. budget_projects (adds `project` and extends `Budget`)
1. documentation (extends `Document`)
1. multiple_buyers (Contract_buyer)
1. partyDetails_scale (details_scale)
1. process_title (title)
1. qualification (preQualification)
1. related_process (RelatedProcess)
1. socialwitness (socialWitness)
1. transaction_relatedMilestone (Transaction_relatedImplementationMilestone)

**Comment by edugomez** [comment]
> We may add suggestions, e.g. that name should be based on a JSON Pointer fragment for the primary field that is being added, or the name of the primary object being added

I think this is a good rule of thumb and we should change extension names if the are far from it, but it would be good to allow some flexibility if it results in a more descriptive name, e.g. adding a new object may be more relevant than adding a non-complex type property to an existing one, but perhaps not so much if the new object has a couple of properties and you are adding ten new properties to the existing one, in which case I may prefer to see a name at least mentioning the extended object. 

 I would definitely replace all camelcases with lowercase plus underscore separator.

**Comment by jpmckinney** [comment]
Guidance is here https://github.com/open-contracting/standard_extension_template#naming-extensions

**Comment by jpmckinney** [comment]
We can re-open if we think we can rename existing extension repositories.
