### ISSUE TITLE
GitHub: People (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#18]
https://github.com/orgs/open-contracting/people

* [x] Describe a policy for who should be an Owner (and make changes if necessary)
* [x] Describe a policy for adding/removing members (and make changes if necessary)

For example, the following members/invitations are not employed by OCP, ODS, or ILDA:

1. anabrandusescu
1. birdsarah
1. ekoner
1. jenit
1. marcelarozo
1. myroslav
1. sdavenpo422

**Comment by timgdavies** [comment]
Relate to #12

**Comment by jpmckinney** [comment]
I've removed the seven people in the issue from the organization.

**Comment by jpmckinney** [comment]
I've drafted the policies in the issue description and dropped owners to me, @timgdavies and @robredpath. Per the policy, we can consider: adding an owner from ILDA, adding another owner from OCP, and/or changing the owners from ODS.
