### ISSUE TITLE
Extensions schema (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#19]
## Extensions

* [x] Delete `versioned-release-validation-schema.json` from all extensions
* [x] Delete any other schema from extensions that are empty objects (`{}`)

`versioned-release-validation-schema.json` can be auto-generated, after applying any extensions to the core release schema.

## standard-maintenance-scripts

* [x] Check that there is no `versioned-release-validation-schema.json` file
* [x] Check that no other schema are empty

## extension_creator

* [x] Update to not generate `versioned-release-validation-schema.json`
* [x] Update to not generate any other schema that would be an empty object (`{}`)

## standard_extension_template

* [x] Delete `versioned-release-validation-schema.json`
* [x] Add docs to readme about which `*-schema.json` files to author
* [x] ~~Remove any empty `*-schema.json` files (to avoid their inclusion in extensions if they're empty)~~ After discussion below, we agreed to leave these, but to encourage ZIP downloads
* [ ] Provide examples for each `*-schema.json` file somewhere (**where do we put examples?**)

## Questions

* Does anything else use `versioned-release-validation-schema.json`?
  * Apparently not
* Determine whether CoVE needs to be updated, in cases where `versioned-release-validation-schema.json` would be relevant
  * Doesn't seem that it's ever relevant
* I had made a note about the release schema referenced in the record package and release package schemas. Is this about the package schemas pointing to the core release schema, and the need for extension users to have package schemas that point to an extended release schema? (And the need for CoVE to use such auto-generated package schemas when validating packages with extended releases?)
  * I think I lacked understanding at the time, but my understanding now is that one reason we declare `"extensions"` in packages is to avoid having to change the `$ref` for the release's schema in the package's schema

@kindly @edugomez @duncandewhurst

**Comment by edugomez** [comment]
> Update to not generate versioned-release-validation-schema.json
>  Update to not generate any other schema that would be an empty object ({})

PR https://github.com/open-contracting/extension_creator/pull/7

**Comment by edugomez** [comment]
> Remove any empty _*-schema.json_ files (to avoid their inclusion in extensions if they're empty)

Not sure about this, as _all_ of them are empty, they are just placeholders really. 

I think it is up to the docs to indicate the right way to go about it. We have this https://github.com/open-contracting/standard_extension_template/tree/add-name-description-guidance#schema-files now (included  in a PR https://github.com/open-contracting/standard_extension_template/pull/9). 

Would that suffice to address this also?:

> Add docs to readme about which *-schema.json files to author

**Comment by edugomez** [comment]
> Delete _versioned-release-validation-schema.json_

PR https://github.com/open-contracting/standard_extension_template/pull/11

**Comment by jpmckinney** [comment]
@edugomez I think it's better to instruct people as to what files to create than to leave empty files in the repository. People are likely to simply leave any unchanged files in their extension. It's not so hard for people to create new files when they need them.

**Comment by timgdavies** [comment]
I find it useful to have the placeholder files, in terms of this operating as a 'template' of what an extension looks like, but then to simply not commit to git the ones that are not being used. 

We could improve the guidance on adding files to git and committing, and perhaps even introduce some extra tests that look for empty files as part of a commit.

**Comment by edugomez** [comment]
> We could improve the guidance on adding files to git and committing, and perhaps even introduce some extra tests that look for empty files as part of a commit.

This sounds good to me. I agree people would tend to leave empty files in the extension, but this can be a solution. @jpmckinney what do you think?

**Comment by jpmckinney** [comment]
We aren't instructing people to download a ZIP of the template. If they fork the template, then the files are already added to git; they would have to go out of their way to remove them. Many extensions also left empty `docs/index.md` files and one left an empty `tests/__init__.py` file.

We can add a default test file to `tests/` that checks whether the repository contains any empty files, and we should instruct people to download the repo as a ZIP file (link to the download) so that adding files is hopefully done more deliberately.

**Comment by kindly** [comment]
@jpmckinney @timgdavies  my instinct is that adding files is more error prone and open to confusion than removing not used files, i.e they have to get the names exactly correct and be confident that that is the correct place to put them.

So personally I would want them in the template but just make it best practice to remove them.

I think encouraging zip download and adding tests for empty files or schema files just with just "{}".  Also making the extension creator remove non used files too.

**Comment by edugomez** [comment]
> Also making the extension creator remove non used files too.
That is done here https://github.com/open-contracting/extension_creator/pull/7

**Comment by jpmckinney** [comment]
Can close this once PRs are closed.
