### ISSUE TITLE
GitHub: Issue labels (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#2]
# Tasks

Delete labels with few open and closed issues:

* [x] Extension - Concessions: 2 issues
* [x] help wanted: 5 issues
* [x] question: 4 issues
* [x] wontfix: 1 issue

Delete overly general labels:

* [x] Focus - Core

# Docs

Every issue in the `standard` repository should have a `Focus` label.

Issues are given tags to indicate their relation to:

* Extension - \*: a specific, large extension
* Focus - \*: a specific theme
* Focus - Codelist: codes and codelists
* Focus - Documentation: new guidance; corrections and clarifications of the documentation; tools for generating, testing and publishing the documentation; UI/UX of standard.open-contracting.org
* Focus - Extensions: new or existing [extensions](http://standard.open-contracting.org/latest/en/extensions/), governance and maintenance of extensions
* Focus - Internationalization: translation
* Focus - Publishing: documentation specific to the publication of data (process, records and releases, merging, splitting, discovery, APIs, etc.)
* Focus - Schema: changes to the JSON Schema (new fields, renamed fields, constraints, etc.)
* Focus - Serialization: data and schema formats other than JSON and JSON Schema
* Focus - Tool: new or existing tools (for validation, etc.)
* Focus - Usecase: a specific reported use case for which the best resolution (schema change, documentation change, no change, etc.) hasn't yet been determined
* Focus - Validation: tools for validation; changes to validations in the schema

----

*Original issue description*

For example, I have no idea what `Focus - Core` means. Isn't anything that's not `Focus - Extensions` focused on core? A lot of the issues whose only focus is 'core' seem to be issues whose focus should (also) be 'schema'.

`Focus - Publishing` seems to be a dead (or overly specific) label, mostly used in 2014. I think it's largely superseded by `Focus - Serialization` and `Focus - Documentation`. (We don't seem to need a deep breakdown of `Focus - Documentation`.)

**Comment by timgdavies** [comment]
Labels have been used fairly inconsistently and ad-hoc to help us through particular periods of organisation around upgrades or consultations. So if you want to have a go at proposing a new scheme of labelling that would be useful going forward - please do go ahead.

**Comment by jpmckinney** [comment]
The current labels are mostly fine. Better to document than to relabel everything. Here's a draft:

----

Issues are given tags to indicate their relation to:

* Extension - \*: a specific, large extension
* Focus - \*: a specific theme
* Focus - Codelist: codes and codelists
* Focus - Documentation: new guidance; corrections and clarifications of the documentation; tools for generating, testing and publishing the documentation; UI/UX of standard.open-contracting.org
* Focus - Extensions: new or existing [extensions](http://standard.open-contracting.org/latest/en/extensions/), governance and maintenance of extensions
* Focus - Internationalization: translation
* Focus - Publishing: documentation specific to the publication of data (process, records and releases, merging, splitting, discovery, APIs, etc.)
* Focus - Schema: Changes to the JSON Schema (new fields, renamed fields, constraints, etc.)
* Focus - Serialization: data and schema formats other than JSON and JSON Schema
* Focus - Tool: new or existing tools (for validation, etc.)
* Focus - Usecase: a specific reported use case for which the best resolution (schema change, documentation change, no change, etc.) hasn't yet been determined

----

Delete labels with few open and closed issues:

* Extension - Concessions: 2 issues
* help wanted: 5 issues
* question: 4 issues
* wontfix: 1 issue

Delete overly general labels:

* Focus - Core

Keep the 0-6 labels in case a team chooses to use them consistently again.

**Comment by jpmckinney** [comment]
I don't know where to put these docs in the page hierarchy, but that's all that's left to do here.
