### ISSUE TITLE
Document search functionality

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#205]
Document how to manually index branches.

Also, document how new websites can be indexed.

Code is at https://github.com/OpenDataServices/standard-search

Fixes:

* [x] Get indexing of `gpa` profile working
* ~~Fix API endpoint to not assume which languages to index~~
    * https://github.com/OpenDataServices/standard-search/issues/8
* ~~Automatically index new branches on profiles (update `.travis.yml`, add secrets to Travis)~~
    * https://github.com/OpenDataServices/standard-search/issues/9
* [x] Check if there is an edge case to fix due to `infrastructure` not being under `/profiles`

**Comment by jpmckinney** [comment]
Related https://github.com/open-contracting-extensions/public-private-partnerships/issues/192

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document and improve search functionality](https://trello.com/c/31F2W1nd/7-document-and-improve-search-functionality)

**Comment by kindly** [comment]
This issue now should be only about improving documentation in the standard development handbook

Issues covering other points are now below:

https://github.com/OpenDataServices/standard-search/issues/8
https://github.com/OpenDataServices/standard-search/issues/9
https://github.com/OpenDataServices/standard-search/issues/10
https://github.com/OpenDataServices/standard-search/issues/11

**Comment by kindly** [comment]
gpa indexing has been fixed and there does not seem to be a issue with infrastructure after looking at the code.

**Comment by robredpath** [comment]
@jpmckinney @kindly when we talked yesterday, we didn't really dig into the detail of what else needed documenting here. If the two items above are enough (at least for now) then I'll leave this as-is, but if we want to add anything else to this round of improvements, now's the time!

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better documentation for standard-search](https://trello.com/c/8jqroXAC/37-better-documentation-for-standard-search)

**Comment by jpmckinney** [comment]
I think it's best to first improve the documentation at source in https://github.com/OpenDataServices/standard-search/issues/11 Once that's done, it'll be clearer whether/what OCDS-specific documentation we might need in the handbook.

**Comment by odscjames** [comment]
@jpmckinney There is now an improved repo readme https://github.com/OpenDataServices/standard-search/blob/master/README.md - do you think we need anything in the handbook? 

Maybe just 2 lines and a link in https://ocds-standard-development-handbook.readthedocs.io/en/latest/systems/servers/ ?

**Comment by odscjames** [comment]
Think this is now closed?
