### ISSUE TITLE
Agree and Document fully the Git Branching scheme we use in different repositories

### ISSUE THREAD

**Issue by odscjames** [open-contracting/standard-development-handbook#221]
If you see https://github.com/open-contracting/deploy/issues/24#issuecomment-534128978 we had some confusion about this. We should resolve that confusion and make sure whatever we decide is documented in the handbook.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agree and Document fully the Git Branching scheme we use in different repositories](https://trello.com/c/lQA916qb/110-agree-and-document-fully-the-git-branching-scheme-we-use-in-different-repositories)

**Comment by odscjames** [comment]
Does #222 close this?

**Comment by jpmckinney** [comment]
I believe so!
