### ISSUE TITLE
GitHub: Disable issues on extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#23]
It's difficult to have a full view of issues across extensions. There are 30 extensions. The situation will get worse as we add more (for EU, GPA, etc.).

I'm also concerned that their invisibility leads to their being forgotten and ignored. If they were in a repository that people regularly access, there's a higher likelihood of the issues getting closed. 

Personally, I favor having all schema-related issues reported to the `standard` repo.

* [x] Alternately, I'm okay with opening a meta extension repo for only extension issues.

* [x] We can easily add a standard content block to READMEs with a link to where to report issues, so that people aren't confused by the lack of an 'Issues' tab.

Presently, there are 13 issues open across 7 repos:

* https://github.com/open-contracting/ocds_metrics_extension/issues
* https://github.com/open-contracting/ocds_multiple_buyers_extension/issues
* https://github.com/open-contracting/ocds_requirements_extension/issues
* https://github.com/open-contracting/ocds_tariffs_extension/issues
* https://github.com/open-contracting/ocds_bid_extension/issues
* https://github.com/open-contracting/ocds_location_extension/issues
* https://github.com/open-contracting/ocds_parties_extension/issues

* [x] I can re-create these if we decide to disable issues.

**Comment by edugomez** [comment]
I agree. Personally, I prefer:

> opening a meta extension repo for only extension issues

I think that not having that in the ```standard``` repo is a good separation of concerns and would allow more granularity when labelling issues without cluttering the ```standard``` repo. I would keep the _Extensions_ label in this repo for overarching extension issues, e.g. strategic changes that would affect all extensions

**Comment by jpmckinney** [comment]
Sounds good - I'll wait for more opinion(s) before going forward.

**Comment by duncandewhurst** [comment]
I agree with @edugomez

**Comment by jpmckinney** [comment]
Done https://github.com/open-contracting/ocds-extensions/issues, except for the last remaining task (adding standard text block to all readmes).

This now makes it easy to see that several easy schema bugs should be fixed: https://github.com/open-contracting/ocds-extensions/issues?q=is%3Aissue+is%3Aopen+label%3A%22Focus+-+Schema%22

**Comment by edugomez** [comment]
[PR](https://github.com/open-contracting/standard_extension_template/pull/8) to add a _README-template.md_ to https://github.com/open-contracting/standard_extension_template with info about submitting issues for extensions.

**Comment by jpmckinney** [comment]
25 PRs opened. I can merge them programmatically if given the go-ahead.

**Comment by jpmckinney** [comment]
I'm merging all 25 PRs next week unless anyone comments before then.

**Comment by jpmckinney** [comment]
Done. All merged.
