### ISSUE TITLE
spellcheck: Add grammer checker

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#240]
https://caderek.github.io/gramma/

cc @duncandewhurst if you have any specific guidance.

**Comment by duncandewhurst** [comment]
I followed the instructions to install via a binary package (I'm not overly familiar with Node.js / NPM) and then used `gramma check [file]` to interactively check individual files.

If using aspell for spell-checking then it's probably worth using `-d typos` to disable spell-checking in gramma, although I forgot to do that.

In case it's useful, here are the words I added to the dictionary:

    ".hernandez@constructiontransparency.org",
    "COFOG",
    "Changelog",
    "Codelist",
    "Codelists",
    "Colaboratory",
    "Fernz",
    "Jupyter",
    "PPPs",
    "UNCEFACT",
    "_static",
    "administrativeEntity",
    "assetAndLiabilityAssessment",
    "assetTransfer",
    "bfernz@open-contracting",
    "biddingDocuments",
    "billOfQuantity",
    "budgetAmendmentApproval",
    "budgetBreakdown",
    "bugfix",
    "cancellationDetails",
    "changelog",
    "codelist",
    "codelists",
    "completionCertificate",
    "conflictOfInterest",
    "consortiaMember",
    "contactPoint",
    "contractAmendment",
    "contractAnnexe",
    "contractArrangements",
    "contractNotice",
    "contractSummary",
    "contractingProcess",
    "contractingProcesses",
    "contractingprocess",
    "current_lang",
    "data@open-contracting",
    "debarments",
    "designReport",
    "discountRate",
    "disqualifiedBidder",
    "docson",
    "documentType",
    "eligibilityCriteria",
    "endDate",
    "endDateDetails",
    "equityInvestor",
    "equityTransferCaps",
    "escalationApproval",
    "eval_rst",
    "feasibilityStudy",
    "finalValue",
    "financeAdditionality",
    "financeArrangements",
    "financialAgreement",
    "financialAuditReport",
    "financialProgressReport",
    "financialStatement",
    "funder",
    "guaranteeReports",
    "hearingNotice",
    "implementers",
    "incorporationCertificate",
    "interestedParty",
    "js",
    "json",
    "jsoninclude",
    "jsonpointer",
    "jsonschema",
    "landTransfer",
    "leadBank",
    "mailto",
    "marketStudies",
    "maxdepth",
    "modificationType",
    "newContractPeriod",
    "newContractValue",
    "ocds-babel",
    "ocid",
    "oldContractPeriod",
    "oldContractValue",
    "otherGovernmentSupport",
    "otherWitness",
    "partyRole",
    "paymentCertificate",
    "physicalProgressReport",
    "pppModeRationale",
    "preferredBidder",
    "privateParty",
    "procurementPlan",
    "procuringEntity",
    "programmes",
    "projectPlan",
    "projectSector",
    "projectStatus",
    "projectType",
    "publicAuthority",
    "publicationPolicy",
    "publishedDate",
    "qualifiedBidder",
    "qualityAssuranceReport",
    "reactively",
    "relatedProject",
    "relatedProjects",
    "requestDate",
    "resettlementPlan",
    "revenueShare",
    "riskComparison",
    "servicePayments",
    "socialImpact",
    "socialWitness",
    "sourceParty",
    "startDate",
    "streetAddress",
    "subContract",
    "submissionDocuments",
    "tariffIllustration",
    "tariffMethod",
    "tariffReview",
    "technicalAuditReport",
    "uri",
    "variationType",
    "winningBid",
    "wy-nav-content"
```
