### ISSUE TITLE
Normative documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#25]
(This issue is to document which parts of the documentation are normative and which are not. Normative sections shouldn't be changed between versions.)

**Comment by timgdavies** [comment]
To give us a straw man to start with:

* The schemas, which populates pages under /schema/ are normative
* All documentation under [/schema/](http://standard.open-contracting.org/latest/en/schema/) in the documentation is normative
* Core extensions **schema** (under /extension/*/ folders) are **normative**, but the **extension  documentation is not** (long run it possible should be - but there are things that we should continue to improve there, whilst respecting backwards compatibility)
* The [implementation guidance](http://standard.open-contracting.org/1.1/en/implementation/levels/) page has been treated as normative by many users. We did not intend it that way (hence the label 'guidance'), but we should consider that users would be upset if this was not treated as normative. 
* The [governance page](http://standard.open-contracting.org/1.1/en/support/governance/) is normative

Pages which are not include in my list, but which perhaps could be:

* [Serialization](http://standard.open-contracting.org/1.1/en/implementation/serialization/)

If my sketch above is right, then we do have normative content mostly in one section, but also some pages scattered elsewhere. 

Should we be marking normative pages in a particular way? Should we look long-term to restructure docs?

How far is the structure of the docs itself something we should guarantee will be fixed (e.g. if we moved the docs around structurally, whilst keeping content, would this matter).

**Comment by Bjwebb** [comment]
> Normative sections shouldn't be changed between versions

Just to flag explicitly, I think we want to make a distinction between semantic and non semantic changes. e.g. We want to be able to fix obvious typos in any part of the docs without needing a new version.

**Comment by jpmckinney** [comment]
That's fine with me. (For context, some, like W3C, don't even correct typos.)

**Comment by jpmckinney** [comment]
Related: http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/documentation/

**Comment by timgdavies** [comment]
I've got a [working draft here](https://docs.google.com/document/d/1xjlAneqgewZvHh6_hwuQ98hbjxRcA2IUqOTJiNGcOf8/edit#) for discussion. 

I need to work more on the implications - but comments on this draft are welcome.

**Comment by jpmckinney** [comment]
Moved to CRM 3077
