### ISSUE TITLE
Explain the use of patternProperties for language-suffixed fields 

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard-development-handbook#250]
From https://github.com/open-contracting/extension-explorer/issues/47#issuecomment-935276292

So that standard contributors and extension authors know that they don't need to define fields for different languages, and that they can instead use the `patternProperties` approach. The content can link to https://standard.open-contracting.org/latest/en/schema/reference/#language

Once the content is ready, add a link from the Extension Explorer.

**Comment by jpmckinney** [comment]
OCDS 1.2 removes patternProperties and does full-file translation instead https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/translations/
