### ISSUE TITLE
Schema style guide: add note on calculated/derived fields and the risk of inconsistent data

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard-development-handbook#253]
If I remember correctly this has come up a few times in modelling discussions, but it isn't documented in the style guide.

@jpmckinney - please could you add something?

**Comment by jpmckinney** [comment]
Which part of this is different from #254? Could you add a link to a relevant discussion?

**Comment by duncandewhurst** [comment]
I'm struggling to find an example, but I think it's come up before when a publisher has wanted to add a field that aggregates the values of other fields.

**Comment by duncandewhurst** [comment]
I realised it would be helpful to include the example that prompted this issue: Assam's procurement data (CRM-7628) includes 3 fields related to bid opening:

* Technical bid opening date
* Price bid opening date
* No of Days b/w Tech and Finance opening

I'm assuming that, in OCDS, we would recommend only including the opening dates and leave it to the user to calculate the number of days between them.

**Comment by jpmckinney** [comment]
Yes - we only include calculated fields in cases where it's often the case that only the calculated value is known or publishable, like the number of tenderers.
