### ISSUE TITLE
Implementation experience

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#26]
How much implementation experience do we want to acquire before making an extension or change final?

At what stages are the different extensions in terms of participation, implementation, etc.? How can we measure this? Should we indicate the maturity of extensions?

**Comment by timgdavies** [comment]
I think this links to a wider question around versioning - and whether we want to think more about a clearer 'Release candidate' phase. 

I think we do have to balance the technical and political dimensions of OCDS here: as for some changes we should be following practice, in others, the goal is to lead practice - and the way a technical community engages with the signalling of 'beta' or 'release candidate' etc. is different from the ways in which a policy community does. 

I think with the information availability research, and potentially through CoVE features, we should consider how to move towards having the data to indicate the maturity of schema elements and extensions - but I think this involves a larger technical and design challenge.

**Comment by jpmckinney** [comment]
Moving requirement for implementation experience to 2.0 Google document.

Tracking use of extensions is reflected in data quality document under discussion of coverage.
