### ISSUE TITLE
GitHub: Milestones (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#27]
https://github.com/open-contracting/standard/milestones

The [Upgrade workflow](https://github.com/open-contracting/standard-development-handbook/issues/4) describes one reason to open a milestone. However, I don't know when milestones are closed.

* 'Version 1.1' has 3 issues open. Why haven't these been closed or removed from the milestone?
* Is 'Post 1.1 tasks' a meaningful milestone? Isn't everything now post 1.1?
* Is there any reason 'Version 1.0.3 bugfix' and its remaining issues aren't closed?
* I don't think we're getting around to the remaining issue in 'Version 1.1.1 - Bugfixes'. Can we remove the issue from the milestone, and close the milestone?

**Comment by timgdavies** [comment]
Milestones should really be closed when the version is deployed.

I think this is a process issue of making sure we have adequate people / time scheduled for end-of-deploy tidy up. 

I've closed the issues noted above.

**Comment by jpmckinney** [comment]
I'm removing the due date for Post 1.1 (as it's overdue, and the milestone description doesn't imply a specific due date).
