### ISSUE TITLE
Alarms and notifications

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#29]
Document what alarm bells ring, and who responds to which with what timeliness. Raised by @timgdavies at helpdesk retreat.

**Comment by Bjwebb** [comment]
Is this the sort of thing we're looking for?:

* Most Travis tests: email the person who made the last commit
* [Extension tester (Travis CRON) emails code [at] opendataservices [dot] coop](https://ocds-standard-development-handbook.readthedocs.io/en/latest/github_integrations/#travis-cron)
* [requires.io emails code [at] opendataservices [dot] coop](https://ocds-standard-development-handbook.readthedocs.io/en/latest/github_integrations/#requires-io)
* [UptimeRobot](http://uptimerobot.com/) and Icinga2 email Open Data Services server notfication email, which goes to @bjwebb and @idlemoor
* [Sentry](https://sentry.io/welcome/) (for OCDS Validator) - goes to all Open Data Services developers, but via individual accounts with Sentry

code [at] opendataservices [dot] coop goes to all Open Data Services devs

**Comment by jpmckinney** [comment]
That works! Also, it seems like six people are default watchers on new GitHub repositories which may be worth mentioning.
