### ISSUE TITLE
Extensions: Add a note on the purpose of an extension's schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard-development-handbook#292]
From https://github.com/open-contracting/standard/issues/582#issuecomment-2486237687:

> In principle, the schema are intended to describe correct structure, but are not intended to describe correct data, except in a few OCDS-specific cases (for example, in principle, there could be a pattern validation property on the ocid field).
> 
> In practice, it is possible that a publisher might want to add additional validation properties to better describe correct data – but as you say, that is not a behavior we've observed. Publishers can validate their data however they like, and I think it's okay to treat such JSON Schema as not being extensions.

**Comment by jpmckinney** [comment]
Closed by 55ed54a
