### ISSUE TITLE
GitHub: Branch management (+cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#3]
## Unexpected non-default branches

These should either be deleted, opened as pull requests, or documented. I've tagged the people who opened the branches.

* [x] https://github.com/open-contracting/ocds-show/branches
  * @robredpath Can we delete the `deploy-to-heroku` branch?
  * @kindly Can we delete the `master` (no new commits and not the default) and `ppp` branches?
  * @timgdavies Can we delete the `ppp-ajax` branch? (merged, but has new commits)
* [ ] https://github.com/open-contracting/ocds-show-ppp/branches
  * @kindly Can we delete the `gh-pages` branch?
* [x] https://github.com/open-contracting/ocds_lots_extension/branches
  * @kindly  Can we delete the `cove-testing` branch?
* [x] https://github.com/open-contracting/standard_theme/branches
  * @Bjwebb Can we delete the `pseudo` and `pseudolocalization` branches?
  * @kindly Can we delete the `basic-ocds-theme` branch?
* [x] https://github.com/open-contracting/standard/branches/all
  * @Bjwebb Can we delete the `1.1-dev-build-script` and `pseudo` branches?

----

(This will be added to a new documentation page:)

Repositories should have only a default branch (usually `master`) and pull request branches. The default branch should be [protected](https://help.github.com/articles/about-protected-branches/) with these options:

* ☑️ Protect this branch
  * ☑️ Require status checks to pass before merging
    * ☑️ Require branches to be up to date before merging
    * ☑️ continuous-integration/travis-ci (if available)
  * ☑️ Include administrators

# Management

* If a branch has no commits ahead of the default branch, and is merged, delete it.
* If a branch has no commits ahead of the default branch, and is not merged but is a month old, delete it.

## Expected non-default branches

* [standard](https://github.com/open-contracting/standard), starting with version 1.0, has an `X.X` branch for the production version of the documentation, and an `X.X-dev` branch for the development version of the documentation. It also has a `latest` branch, which must be kept up-to-date with the most recent `X.X` branch.

**Comment by jpmckinney** [comment]
Should we set [`CODEOWNERS`](https://help.github.com/articles/about-codeowners/) for some repositories? It's not obvious who to ping about open issues or pull requests otherwise.

**Comment by jpmckinney** [comment]
I've protected all default branches (using the GitHub API) with the configuration in the issue description.

**Comment by Bjwebb** [comment]
>  https://github.com/open-contracting/standard_theme/branches @Bjwebb @kindly I assume we keep the master branch as a reference to the upstream repository.

That's right. I think this is the same case as json-schema-random

> At what point do we delete *-dev branches? If never, we should protect those branches.

Never.

> Why are there not x.x branches for all versions? Not all prior versions are built at standard.open-contracting.org. If we need these branches forever, we should protect them.

Versions prior to 1.0 were built from tags rather than branches. Are those what you're asking about?

**Comment by jpmckinney** [comment]
@Bjwebb So I'm a little confused.

# 1.1-dev

It makes sense to keep this named as-is, as the most conservative assumption is for there to be another minor release (1.1.2). However, I'm tempted toward the default branch being `master` instead of having to rename/switch default branches. This may be based on a misunderstanding of what utility any of these `*-dev` branches have, which I go over below.

# 1.1

It shows as two commits ahead of `1.1-dev`, but only because of (empty) merge commits. Otherwise it's 6 commits behind `1.1-dev`. `1.1` is not an extant version number though; we released `1.1.0` not `1.1`. It seems like it's meant to stand for the `1.1.*` series, like `1.0` for the `1.0.*` series, and that we should therefore protect it.

# 1.0.3-dev and 1.0-dev

`1.0` (protected) is the most up-to-date branch for the 1.0.* series. `1.0-dev` just lacks two (empty) merge commits in `1.0`. And `1.0.3-dev` is 3 commits behind `1.0-dev`, even though it's the most recent version in that series. Do we really want to keep both `1.0-dev` and `1.0.3-dev` forever? If so, why isn't there a `1.0.2-dev` or `1.0.1-dev`? It seems like only `1.0` is needed forever.

# 1.1.1-dev

Same comments as `1.0.3-dev`. It seems we can delete it considering we have `1.1` and `1.1-dev`.

# 1.0.2

This branch would make sense if we also had a `1.0.3` and `1.1.1` (without `-dev` suffix), but we don't, which makes me wonder why we have it at all.

**Comment by jpmckinney** [comment]
Also in `standard`, I'm confused by the existence of `master` and `latest`. `tmp-translation` looks like it could be deleted. I'm assuming `ppp-extension` was opened before we decided to do that work in a new repo, and that we can delete that branch.

There's unmerged code in `mapping_sheet`, `pseudo` and `1.1-dev-build-script`. The first seems like it can be merged safely. https://github.com/open-contracting/mapping-sheet-generator/issues/6 is open to determine what to do with the new script. For the other two, it's unclear if they are abandoned and defunct, or potential future work.

**Comment by Bjwebb** [comment]
> It seems like it's meant to stand for the `1.1.*` series, like `1.0` for the `1.0.*` series, and that we should therefore protect it.

Yes. It should be protected.

I think the original intent was to not have patch versions in branches, only in release IDs. Usage of branches for patches has basically been inconsistent. We might want to delete them all, but I'm not sure if they're linked to from e.g. the mailing list.

> However, I'm tempted toward the default branch being `master` instead of having to rename/switch default branches.

I think the reason for avoiding `master` was to make it clear from the branch name what version it will be included in. Whereas with `master`, we'd have to pick a point for the transition from going into 1.1, to going into 1.2. And, after that transition, what branch should be used for working on a set of changes to go into 1.1?

> Also in `standard`, I'm confused by the existence of `master` and `latest`. 

Someone's pushed `master` by accident, so I've deleted.

`latest` currently tracks `1.1`. This is needed to trigger a build with "latest" as the version for replacing in the schema etc. https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/utils/translate_schema.py#L36

> `tmp-translation` looks like it could be deleted

Yes, deleted.

> I'm assuming `ppp-extension` was opened before we decided to do that work in a new repo, and that we can delete that branch.

Yes, it's where the ppp extensions was worked on before the new repo. History wasn't carried over though, so we may want to keep the branch to preserve history.

**Comment by jpmckinney** [comment]
I've now protected `latest`, `1.1` and `1.0-dev`.

I don't think we need to be heroes about broken links. I'd rather not pollute the repository with dead branches just because something linked to them once. So, nominate deleting patch branches: `1.1.1-dev`, `1.0.3-dev` and `1.0.2`.

Ah, right. I remember now when working on Drupal, there was a `9.x` branch for the unreleased future version, and `8.5.x`, `8.4.x` etc. for each minor version. However, they didn't have both 'production' and 'development' branches for each minor version. Do we need both so that we can make small changes to released minor versions without doing a patch version?

I suppose we can keep the `ppp-extension` branch, but I'm not sure that history will ever be relevant.

**Comment by jpmckinney** [comment]
Also, re: broken links, we should really only be linking to builds, and ReadTheDocs is capable of holding a build even if its source is gone. I don't think we ought to be linking to GitHub branches. GitHub supports links that instead use commits, which are permalinks (unless you destroy history). We should use links that bind us to keeping junk branches.

**Comment by jpmckinney** [comment]
Following the above discussion of version branches, what is the intention of having `master` and `1.0` on [`public-private-partnerships`](https://github.com/open-contracting/public-private-partnerships/branches/all)?

**Comment by duncandewhurst** [comment]
I'm not sure why we have a `1.0` branch on [`public-private-partnerships`](https://github.com/open-contracting/public-private-partnerships) as we haven't decided on a version number for the PPP profile

I have been creating PRs against `master` and as far as I'm aware this is what is used to create the live deploys

I may be wrong though, @Bjwebb, @kindly could you confirm whether we can remove the `1.0` branch?

**Comment by Bjwebb** [comment]
I added 1.0 as the live deploy.

**Comment by jpmckinney** [comment]
Hmm, `1.0` is gone now.

**Comment by timgdavies** [comment]
Thanks for all the clean-up here: I'm learning a lot about good practices to follow in future :) 

### Extension registry 

On  https://github.com/open-contracting/extension_registry/branches I've removed gh-pages. 

For the extension registry version number branches @kindly will be able to contribute to the documentation on this. 

### Version number and dev branches and deployment

I've wondered for a while whether we should be using tags rather than branches to freeze particular versions? I guess this might have quite an impact on our deployment approach, but worth exploring. 

In terms of maintaining links, I think ideal would be for us to have a good mechanism to decide whether a past build (e.g. a particular branch for testing a version, feature or translation) should remain as an archived state, or should be replaced by a redirect to the final version of that. 

### PPP branch in standard

I think this can be removed. 

### Linking to commits

Good point. We should add a note on this to the handbook - as not sure it's something I've been doing by default when engaging people.

**Comment by duncandewhurst** [comment]
> Hmm, `1.0` is gone now.

@jpmckinney we've removed `1.0` since we didn't intend to declare a version `1.0` (it was carried over unintentionally in the theme from the core OCDS docs)

@timgdavies will write up an issue on versioning/governance for the PPP extension

In the meantime we'll keep `master` and add a `live` branch when we do the final deploy for the launch of the PPP profile

**Comment by jpmckinney** [comment]
@kindly @timgdavies @robredpath @Bjwebb I've updated the issue description to be clearer on which old, unexpected, unmerged branches need to be either: deleted, opened as pull requests, or documented.

**Comment by timgdavies** [comment]
I've addressed OCDS Show branches. The others we'll make sure get picked up in next OCDS focus week, so we can work through systematically.

**Comment by jpmckinney** [comment]
@kindly I deleted `cove-testing` from `ocds_lots_extension` as it seems to have been only for testing: https://github.com/open-contracting/ocds_lots_extension/commit/372563148e3ebe437221b5cc1375c694f417eb78

**Comment by jpmckinney** [comment]
@Bjwebb I deleted `pseudo` and `pseudolocalization` from `standard_theme` as it seems they were only for testing.

https://github.com/open-contracting/standard_theme/commit/38c9c932b66a7a8c5e387d9eea01d9db62cdcd38
https://github.com/open-contracting/standard_theme/commit/047a288e2eec8e8e9fbf0d1af66a4ddfe4dabe45

**Comment by jpmckinney** [comment]
@kindly The changes in `basic-ocds-theme` seem to have been committed independently, so deleting the branch. https://github.com/open-contracting/standard_theme/commit/1e389668c0bebfd13b90fc690ba0a1c3a03ffd94

**Comment by jpmckinney** [comment]
@Bjwebb `pseudo` on `standard` is related to the `pseudo` branch I deleted on `standard_theme`, so deleting it as well.

https://github.com/open-contracting/standard/commit/6f15cb54f3583eeac52c12645950d966d0453ba8

**Comment by jpmckinney** [comment]
@timgdavies committed changes similar (or identical) to `1.1-dev-build-script` in https://github.com/open-contracting/standard/commit/bc2893855f3bf0bdfdc289e347f0225306dc7ed7, so deleting that branch.

https://github.com/open-contracting/standard/commit/6842e991bbd67fddbf0dd22900b027afbbdc858d

**Comment by jpmckinney** [comment]
Created https://github.com/open-contracting/ocds-show-ppp/issues/2 for the last branch. Closing.

**Comment by jpmckinney** [comment]
Documentation is at http://ocds-standard-development-handbook.readthedocs.io/en/latest/github/branch_management/

Sorry, @timgdavies, somehow missed your comment. However, after inspection, it seems most branches could be deleted. They are easily recoverable by clicking the commit links in my comments (most were only one commit).
