### ISSUE TITLE
Non-upgrade workflow

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#30]
For typos and changes to non-normative documentation. At present, I don't believe we have such a workflow.

Proposed criteria for permissible commits between upgrades:

* Changes that produce no visible changes to outputs, the outputs being:
  * [standard.open-contracting.org](http://standard.open-contracting.org) HTML pages. If a change to a Markdown file results in no changes to translations, then that change is considered invisible.
  * CSV files (mostly codelists)
  * JSON files (mostly schema)
    * `release-schema.json`
    * `release-package-schema.json`
    * `record-package-schema.json`
    * `versioned-release-validation-schema.json`
    * `extension.json`
  * `LICENSE` and `LICENSE.md` files
* Whitespace changes that produce no visible changes to outputs.
  * Indentation changes in JSON files are allowed.
* Typo fixes that result in no change to meaning or behavior.
  * Fixing a typo in a code in a codelist CSV file, or in a field name like `uniqueItems` in a JSON Schema file, would change behavior. Fixing typos in `description` columns or `description` fields wouldn't change behavior.

Once we agree the set of criteria, I can write a script to test PRs against the criteria, in order to generate a list of PRs that can be merged. We can then either review those PRs manually, or trust that the changes are okay, and merge them programmatically using another script.

**Comment by Bjwebb** [comment]
@robredpath is there anything to add to this from our 1.1 retro?

**Comment by timgdavies** [comment]
Agreed that it would be really handy to have script that can feedback when PR can just be merged right away.

**Comment by jpmckinney** [comment]
I made a first cut at a script for reviewing PRs on the command line: the `rake pulls:compare` task in https://github.com/open-contracting/standard-maintenance-scripts

Related to determining what is normative in #25
