### ISSUE TITLE
Cleanup inline triple backticks in documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#32]
Why do we triple-backtick inline, e.g.

        The ```camelCase``` field is…

**Comment by timgdavies** [comment]
Um, because I think I thought at some point in time I needed to do that... and then got into the habit of it.

Happy to get out of that if it's a bad habit.

**Comment by jpmckinney** [comment]
It confuses Markdownlint (though that's a bug in Markdownlint), but anyhow, triple-backticks should only be used to fence code blocks.

**Comment by timgdavies** [comment]
Ok. Happy to put a clean-up issue to fix this next time we do a big update of docs (but let's leave it for the moment to not upset current translations that are in progress etc.)

**Comment by jpmckinney** [comment]
Sounds good. I didn't end up having more miscellaneous questions, so renaming this issue.

**Comment by jpmckinney** [comment]
I replaced triple backticks in extensions.
