### ISSUE TITLE
How are files like `bids.md` kept in sync with the extension's README.md?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#33]
Is this done manually?

**Comment by jpmckinney** [comment]
Related https://github.com/open-contracting/standard/pull/550

I think @Bjwebb can also answer this issue.

**Comment by Bjwebb** [comment]
My understanding is that it's been previously done manually. I've started writing a script to automate it, @timgdavies is this a useful thing to pursue further (programatically adding metadata sections etc.)

**Comment by timgdavies** [comment]
It is done manually right now.

Yes: a programatic approach would be good - providing we're careful in our process about picking up the frozen versioned copy of the extension, and that for the docs author it's easy to work out what is going on. 

Being able to more consistently display the meta-data, extension docs, schema for an extension and codelists (and in future, examples) for that extension would be very helpful I think - and might let us simplify the extension README files so they don't duplicate codelist, examples or other contents would be good. 

Might be useful to have wider design conversation about this before lots of code is written.

**Comment by Bjwebb** [comment]
Writing a basic script wasn't too much work, so I did that - https://github.com/open-contracting/standard/pull/550/files#diff-938ec24ad4e51596153df9258530240f
This is now documented as a deployment step in the handbook https://ocds-standard-development-handbook.readthedocs.io/en/latest/deployment/standard-live/#pulling-extension-documentation

**Comment by jpmckinney** [comment]
This answers my query, so feel free to close :)
