### ISSUE TITLE
Document translation of extensions and integration into documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#35]
Tasks:

* [x] Document extensions’ maintenance process http://ocds-standard-development-handbook.readthedocs.io/en/latest/extensions/
* [x] Document extensions' deployment process http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/
* [x] Document differences in process for community/core extensions (covered in above)
* [x] Document translation of extensions and integration into documentation: http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/extensions/
* [ ] ~~Improve the consistency of READMEs across extensions~~ open-contracting/ocds-extensions#44

----

Questions:

* Where should community extensions live? Must they all live in `open-contracting`?
  * No, they can live anywhere

**Comment by timgdavies** [comment]
On the question: No. We have not made a policy on this so far - but I've been assuming community extensions can be maintained elsewhere. We might even want to move them out of main open-contracting org, so we are only keeping core extensions there.

**Comment by jpmckinney** [comment]
Maintenance process documented: http://ocds-standard-development-handbook.readthedocs.io/en/latest/extensions/

Moved "Improve the consistency of READMEs across extensions" to https://github.com/open-contracting/ocds-extensions/issues/44

**Comment by jpmckinney** [comment]
Actually, still need to document translation of extensions: http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/extensions/

**Comment by jpmckinney** [comment]
Translation of extensions is same as everything else: the build treats the Markdown and CSV files like others.
