### ISSUE TITLE
Tools support for extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#36]
CoVE supports extensions. What about mapping templates, and other tools? We can start by listing all the tools that require support.

* [x] CoVE
* [ ] ocds-show: doesn't support 1.1 https://github.com/open-contracting/ocds-show/issues/16
* [x] [ocds-faker](https://github.com/open-contracting/ocds-faker): seems like it should already support extended schema?
* [x] [mapping-sheet-generator](https://github.com/open-contracting/mapping-sheet-generator): seems like it should support already extended schema?
* [x] [ocds-tabulate](https://github.com/open-contracting/ocds-tabulate): seems like it should already support extended schema?
* [x] [flatten-tool](https://github.com/opendataservices/flatten-tool/): seems like it should already support extended data?
* [ ] [sample-data](https://github.com/open-contracting/sample-data): not sure if we want to add sample data for extensions
* [ ] mapping templates https://github.com/open-contracting/ocds-extensions/issues/35

Things that don't require extension support:

* ocds-merge
* json-merge-patch
* json-schema-random

**Comment by edugomez** [comment]
The following tools support extended schema:
- ocds-faker
- mapping-sheet-generator
- ocds-tabulate (PR to fix issue https://github.com/open-contracting/ocds-tabulate/pull/6)
- flatten-tool 

The other tools:
- ocds-show: as mentioned, needs some more work, there's an [issue](https://github.com/open-contracting/ocds-show/issues/16) for it 
- sample-data: we could add some packages with extensions and releases using those extending fields. The problem is the schema needs to be extended first. One easy solution would be to add the extended schemas to the repo and make ```validate.sh``` a command line tool accepting arguments and/or options.
- mapping templates: where are those?

**Comment by jpmckinney** [comment]
Mapping templates are the spreadsheets that can be found at https://www.open-contracting.org/resources/

**Comment by edugomez** [comment]
Mapping templates contain release level fields only (no package) so it doesn't provide a mechanism to declare extensions.

**Comment by edugomez** [comment]
@julijahansen pointed out that [ocds-merge](https://github.com/open-contracting/ocds-merge) is missing from the list. ocds-merge has no notion of schema and manipulates JSON data as is, so I _think_ extension support doesn't apply to it.

**Comment by jpmckinney** [comment]
I agree that ocds-merge doesn't require explicit extension support.

Re: mapping templates, I'm not sure how we generate them (whether manually, semi-automatically, automatically), but as a future request we can consider having an option of generating templates with selected extensions (not sure where to log that or who leads on mapping templates?).

**Comment by julijahansen** [comment]
As far as I know Duncan generated the mapping templates (manually?), so I'm not sure what our plans are re: future template development work. I guess we should discuss our wider strategy and work pipeline to see how it all fits in.

**Comment by edugomez** [comment]
@timgdavies has also mentioned generating templates (including extensions) programmatically.

@jpmckinney if this issue was meant to evaluate extension support for tools, can we open new issues as neeed (e.g. generate mapping templates with extensions programmatically) and close this one?

**Comment by jpmckinney** [comment]
I created that issue for templates. It seems that this issue is complete.

**Comment by edugomez** [comment]
One last thing before closing this one, what about sample data, are we happy with it as it is?

**Comment by jpmckinney** [comment]
I think samples of extensions should go in the extensions themselves (we currently put a snippet in the readme, but I have an issue to create sample files https://github.com/open-contracting/ocds-extensions/issues/34).

**Comment by edugomez** [comment]
:+1:

**Comment by jpmckinney** [comment]
Okay, closing – unless I misunderstood something :)
