### ISSUE TITLE
Remove .gitattributes and .gitignore from all extensions (cleanup)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#40]
The two files are *way* overspecified and don't match *any* paths in the repositories. I advocate against the inclusion of any file that serves no purpose.

**Comment by jpmckinney** [comment]
@duncandewhurst Seems you added a lot of these, so want your opinion.

**Comment by duncandewhurst** [comment]
@jpmckinney please go ahead and remove them (if you have a quick way of doing that)

I think these were added when I was using the Github Windows GUI (which also seems to add arbitrary emojis to your commits)

**Comment by jpmckinney** [comment]
Done (programmatically) except for [ocds_related_process_extension](https://github.com/open-contracting/ocds_related_process_extension) because it's [not in the registry](https://github.com/open-contracting/extension_registry/issues/59).
