### ISSUE TITLE
GitHub: Requires.io

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#7]
[`sample-data`](https://requires.io/github/open-contracting/sample-data/requirements/?branch=master) and [`standard`](https://requires.io/github/open-contracting/standard/requirements/?branch=1.1-dev) have Requires.io integrations.

* [x] Document how we use Requires.io
* [ ] Add badge to readme (or somewhere)

**Comment by Bjwebb** [comment]
Documented in https://github.com/open-contracting/standard-development-handbook/pull/45

I think we don't need a badge, because what we really care about is this notification emails.

**Comment by jpmckinney** [comment]
Since we only have two using it, we don't need badges. If we start using requires.io across all Python projects, we can then consider having a badge dashboard like http://jpmckinney.github.io which is helpful to anyone wanting to monitor a large number of projects and who hasn't been subscribed to emails from time immemorial.
