### ISSUE TITLE
Document how to create new OCDS profiles

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#70]
Beyond what is covered in http://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/ – need to know about setting up a skeleton profile repository, etc.

**Comment by jpmckinney** [comment]
* [ ] Document how to use `translate-toolkit` to copy translations from core OCDS docs to a new profile @Bjwebb

**Comment by robredpath** [comment]
@timgdavies - could you provide a high-level overview of this? In particular, the components and a broad outline of the process? Then, I figure @Bjwebb can take a second look and fill in the details, then @jpmckinney can test it for the next profile he's working on.

**Comment by jpmckinney** [comment]
Done: https://github.com/open-contracting/profile_template

Am updating handbook as well.
