### ISSUE TITLE
Expand extension authoring guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#75]
# `id` fIelds

Re: having an `id` for any new objects introduced: In core, we don't have an `id` for `Planning`, `Implementation`, `Address`, `ContactPoint`, `Value`, `Period`.

We should author guidance about when to add an `id` to an object, e.g.

* not required for every building block (like `Value`)
* not required if the object only exists to nest properties (like `Implementation`)
* recommended if the object needs to be referenced from elsewhere
* recommended if the concept that the object represents has an ID in the real world

# Nullable fields

Re: http://standard.open-contracting.org/latest/en/schema/merging/

In general, optional fields should be nullable, and required fields should be non-nullable, but this isn't always the case. See https://github.com/open-contracting/standard/issues/630

# Definitions

* Describe when to define an object under `definitions`, instead of inlining its definition.
* Definitions should be capitalized. (Note: `record` is lowercase in `record-package-schema.json`)

**Comment by timgdavies** [comment]
I've addressed id fields, null and definitions usage in this PR draft: https://github.com/open-contracting/standard-development-handbook/pull/107

**Comment by jpmckinney** [comment]
Re:

> (To be confirmed:) Any non-required property pointing to an array of objects should not allow `null` as a value, as array entries should be explicitly tagged for removal following the pattern outlined in [Standard#232](https://github.com/open-contracting/standard/issues/232) 

That's the expected behavior, and this test checks for it: https://github.com/open-contracting/standard-maintenance-scripts/blob/f2c9c3b/tests/test_json.py#L269-L275
