### ISSUE TITLE
Technical section is missing from the TOC

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard-development-handbook#77]

**Comment by jpmckinney** [comment]
Do you mean the `coding` directory? https://github.com/open-contracting/standard-development-handbook/tree/master/docs/coding

**Comment by Bjwebb** [comment]
I meant https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/

**Comment by jpmckinney** [comment]
Aha, well it seems each is missing from different TOCs :)

For `technical`, I think it just needs to be edited to `technical/index`

**Comment by jpmckinney** [comment]
`technical/index` closed by https://github.com/open-contracting/standard-development-handbook/pull/80/commits/10bd22476cfb7de20a74b73dd3d8c5b1c06a0644
