### ISSUE TITLE
Enable issues on OpenDataServices/sphinxcontrib-jsonschema

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#78]
I wanted to create an issue about writing a test so that the `jsonschema` directive raises an error if a `collapse` value doesn't exist, as in https://github.com/open-contracting/standard/issues/596

**Comment by Bjwebb** [comment]
Issues enabled https://github.com/OpenDataServices/sphinxcontrib-jsonschema/issues
