### ISSUE TITLE
Document servers' deployment setup

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#86]
e.g. fundamendals like Apache, sshd config, etc.

**Comment by robredpath** [comment]
@jpmckinney which servers are you thinking of? The validator? The config for that is in github.com/OpenDataServices/opendataservices-deploy , so is the task here to write a bit of a guide to what, where and who?

**Comment by jpmckinney** [comment]
http://ocds-standard-development-handbook.readthedocs.io/en/latest/systems/servers/ lists some servers. If https://github.com/OpenDataServices/opendataservices-deploy is used for all of those, we can just add a sentence with a link to that repo to that handbook page.

I imagine the readme is sufficient for anyone familiar with Salt, but there may be an opportunity to document the steps to setup a server from scratch – e.g. in case of a major failure.

Rob at Dogsbody sent me a PDF of the commands run to set up the Redmine server, which I can share – I haven't checked whether there are security concerns with sharing more publicly.

**Comment by Bjwebb** [comment]
> If https://github.com/OpenDataServices/opendataservices-deploy is used for all of those

Yes, it is.

We have also have an internal wiki with steps to get set up, and create a new server.

**Comment by jpmckinney** [comment]
Cool, I wasn't sure where that link in the readme led. So let's add a sentence with a link to that repo to that handbook page, and we can close this.

**Comment by jpmckinney** [comment]
Closed by #98
