### ISSUE TITLE
Add step to run fetch_currency_codelist.py

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#89]
standard/schema/utils/fetch_currency_codelist.py was introduced in https://github.com/open-contracting/standard/pull/607

**Comment by Bjwebb** [comment]
I'm not sure if this belongs in deploment.md, as it's not really a deployment step, but I'm not sure where else to put it.

**Comment by jpmckinney** [comment]
I suppose we should instead commit to run it at least once a year (considering the list is [updated at least once a year](https://github.com/open-contracting/standard/pull/607#issuecomment-339093306)). We can create a page for periodic maintenance tasks. I can then add some tasks from https://github.com/open-contracting/standard-maintenance-scripts

**Comment by jpmckinney** [comment]
I put a reminder in deployment.md as I can't think of an appropriate place to put this. We can move it later.
