### ISSUE TITLE
Add CRM plugin(s) to reduce the visual clutter of long issues. In order of priority:

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard-development-handbook#92]
* [x] [redmine_collapse_quotes](https://github.com/commandprompt/redmine_collapse_quotes) to avoid repeating quoted parts of emails.
* [x] [redmine-collapsed-journals](https://github.com/stgeneral/redmine-collapsed-journals) to optionally hide the journal entries like changes in status.
* [ ] [journal_folder](http://www.redmine.org/plugins/journal_folder) to limit the number of comment shown when first opening an issue.

**Comment by timgdavies** [comment]
We have the views_customize plugin already installed, which lets us add jQuery directly to pages.

I've got the following snipped from collapse quotes for testing

```javascript

$(function() {
  $('#history > div.has-notes').each(function(i) {
    $(this).find("blockquote").each(function(i) {
      q = $(this);
      if (q.height() < 100)
        return;
​
      a = '<a class="toggle-quoted-text quoted-text-collapsed" href="#" onclick="return toggleQuotedTextVisibility(this);">...Show quoted text...</a>';
      q.before(a);
      q.hide();
    });
  });
});
​
function toggleQuotedTextVisibility(a) {
  a = $(a);
  q = a.next("blockquote");
  q.toggle();
  // reflect current visibility state
  if (q.is(':visible')) {
    a.text("...Hide quoted text...");
    a.removeClass("quoted-text-collapsed");
    a.addClass("quoted-text-expanded");
  } else {
    a.text("...Show quoted text...");
    a.addClass("quoted-text-collapsed");
    a.removeClass("quoted-text-expanded");
  }
  return false;
}

```

and will look at the best way to implement the other two requests shortly.

**Comment by timgdavies** [comment]
I've added the quoted text, and a toggle to hide change of status journal entries.

I've not added a journal_folder behaviour yet. 

I have my account set to display journal entries in reverse chronological order, which makes it easy to see the latest updates without scrolling.

**Comment by jpmckinney** [comment]
Those two are sufficient. Browsing a long issue like https://crm.open-contracting.org/issues/2217 is now much easier with quoted text hidden by default, and with the option to hide journal entries.
