### ISSUE TITLE
Document internal process around OCID prefixes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#93]
@julijahansen, you just generated one, so can you document your steps in this issue (or submit a pull request)?

**Comment by julijahansen** [comment]
Our current ocid prefix generation process is as follows:
1) Open the ocid prefix spreadsheet: https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/edit#gid=719166812
2) Click the OCID tab at the top (next to Help) - this will create a new randomly generated ocid prefix in a new row
3) Add all other relevant details like Organization, Contact Person, Registration date etc.

**Comment by jpmckinney** [comment]
Do we know why we have the Identifier Scheme and Organization Identifier columns? Should those be filled in, or have they been abandoned? Most government agencies have no coverage within any scheme. We could fill the columns for corporations, but they are not a strong focus.

We may want to have some guidance for:
* Organization (e.g. whether to include the English translation, the original language, or both; how we validate the official name for the organization)
* Used for (whether to keep it, and if so whether to try to have URLs for the most part, as the descriptive text is sometimes uninformative)
* Contact person (how we decide or validate who this person ought to be)

I added columns for:
* Publishing?: Whether the prefix is being used to publish OCDS data
* Validated?: Whether that OCDS data validates
* CRM: A link to the CRM issue in which the prefix was requested (to more easily access that context, particularly for organizations that are not yet publishing)

**Comment by jpmckinney** [comment]
I removed the Identifier Scheme and Organization Identifier columns as we only have two entries filled in (Web Foundation and NRGI).

**Comment by jpmckinney** [comment]
I added this as internal documentation, as it's less tightly bound to the standard – and the process might also change soon if we develop a self-service option. 

https://docs.google.com/document/d/1is5z4EvQArSSVE0R_CL-_Ca2ZSgIO8xNxAhgDCV3PUk/edit#
