### ISSUE TITLE
When do we delete GitHub Projects?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#95]
We use projects to organize sprints, but I anticipate that at some point we will have a lot of projects and it will make things unclear and cluttered. https://github.com/orgs/open-contracting/projects

I updated the status of cards in the two non-active boards, and I think they are at a stage that those two boards can be deleted. We can perhaps end every sprint with a check-in on the board, and a decision can be made as to whether to carry over cards to a new board, or just abandon them.

Alternately, we may be moving towards having perpetual boards, in which case we don't need to agree a process around this – we just need to decide what to do with the two old boards.

**Comment by robredpath** [comment]
As I see it, there are two types of work that we organise with project boards on GitHub:
- Sprints that have a small number of focussed deliverables, such as "make OCDS Show do this new thing", or "improve these four areas of the validator's interface". 
- Periods of time where we focus our development attention on a set of work that is refined, reprioritised and reorganised during regular check-ins with OCP. 

The first kind of work lends itself to short-term boards - we agree on a prioritised set of work items, make the progress that we can, and at the end of the sprint, agree on whether the remaining work should be dropped, reframed or carried over to a future sprint. 

The second kind of work lends itself to longer-lived boards (I'd argue against entirely permanent boards as I can see them becoming quite disorganised - it can be psychologically very hard to remove something from a board, as it feels like you're saying that it will never get done). 

So, I'd suggest that we: 
- Schedule a call this week to review the "Polishing tools for 1.1" and "Tweaks & Docs Sprint 2017-08-21 - 2017-09-01" boards, to close them off while ensuring that any work that's undone is correctly prioritised
- Review the "Quick & Easy" and "Priority" boards at the same time, to see if we can combine them into a new board (tentatively) called "Maintenance / incremental improvements late 2017/early 2018". 
- Commit to discussing priorities for the next sprint (starting 13th Dec) with both areas of our work in mind, and to having a higher-level conversation around Feb next year to populate the 'mid 2018' versions of those boards. 

How does that sound?

**Comment by jpmckinney** [comment]
That all sounds good!

**Comment by jpmckinney** [comment]
Reassigning to schedule call to go over first two bullets.
